optimize:
  filename_metadata: datapackage.json
  solver: cbc
  debug: true
  receive_duals: false
  el_gas_relation: electricity_gas_relation
  el_key: electricity  # prefix of keywords for gas electricity relation
  gas_key: gas  # prefix of keywords for gas electricity relation

plot_scalar_results:
  agg_regions: true
